#ifndef LEVEL_H_
#define LEVEL_H_
#include<stdlib.h>
#include<stdio.h>
#include<SDL/SDL.h>
#include<SDL/SDL_image.h>
#include<SDL/SDL_mixer.h>
#include<SDL/SDL_ttf.h>


void level1(SDL_Surface* game_arr,SDL_Surface* game_home,Mix_Chunk* scratch_sword,SDL_Surface* sword,SDL_Surface* points,SDL_Surface* minute0,SDL_Surface* minute1,SDL_Surface* minute2,SDL_Surface* minute3,SDL_Surface* minute4,SDL_Surface* minute5,SDL_Surface* minute6,SDL_Surface* minute7,SDL_Surface* minute8,SDL_Surface* minute9,Mix_Chunk* scratch_flash,Mix_Chunk* scratch_cristal,SDL_Surface* speed2,SDL_Surface* score_speed0,SDL_Surface* score_speed1,SDL_Surface* score_speed2,SDL_Surface* score_speed3,SDL_Surface* score_speed4,SDL_Surface* score_speed5,SDL_Surface* score_speed6,SDL_Surface* score_speed7,SDL_Surface* score_speed8,SDL_Surface* score_speed9,SDL_Surface* speed1,SDL_Surface* cristal1,SDL_Surface* cristal2,SDL_Surface* cristal3,SDL_Surface* cristal4,SDL_Surface* cristal5,int *et1,Mix_Music *musique,Mix_Music *desert,Mix_Chunk* scratch,Mix_Chunk* scratch_hit,Mix_Chunk* scratch_jump,Mix_Chunk* scratch_coin,Mix_Chunk* scratch_key,Mix_Chunk* scratch_etoile,Mix_Chunk* scratch_victory,Mix_Chunk* scratch_fail,int *coon,int *n1,SDL_Surface* win,SDL_Surface* etoile,SDL_Surface* etoile1,SDL_Surface* next_level,SDL_Surface* next_level1,SDL_Surface* home1,SDL_Surface* score_level,SDL_Surface* game_over,SDL_Surface* home,SDL_Surface* arr_plan,SDL_Surface* key1,SDL_Surface* key2,SDL_Surface* key3,SDL_Surface* key4,SDL_Surface* key5,SDL_Surface* key6,SDL_Surface* num0,SDL_Surface* num1,SDL_Surface* num2,SDL_Surface* num3,SDL_Surface* num4,SDL_Surface* num5,SDL_Surface* num6,SDL_Surface* num7,SDL_Surface* num8,SDL_Surface* num9,SDL_Surface* coin1,SDL_Surface* coin2,SDL_Surface* coin3,SDL_Surface* coin4,SDL_Surface* coin5,SDL_Surface* coin6,SDL_Surface* coin7,SDL_Surface* coin8,SDL_Surface* game_play,SDL_Surface* game_pause,SDL_Surface* heart,SDL_Surface* screen,SDL_Surface* background1,SDL_Surface* background11,SDL_Surface* perso,SDL_Surface* perso1,SDL_Surface* perso2,SDL_Surface* perso3,SDL_Surface* persop,SDL_Surface* perso1p,SDL_Surface* perso2p,SDL_Surface* perso3p,SDL_Surface* b1enemi11,SDL_Surface* b1enemi12,SDL_Surface* b1enemi13,SDL_Surface* b1enemi11p,SDL_Surface* b1enemi12p,SDL_Surface* b1enemi13p,SDL_Surface* b1enemi21,SDL_Surface* b1enemi22,SDL_Surface* b1enemi23,SDL_Surface* b1enemi21p,SDL_Surface* b1enemi22p,SDL_Surface* b1enemi23p,int *continuer);
/*---------------------------------*/
void level2(SDL_Surface* game_arr,SDL_Surface* game_home,Mix_Chunk* scratch_sword,SDL_Surface* sword,SDL_Surface* points,SDL_Surface* minute0,SDL_Surface* minute1,SDL_Surface* minute2,SDL_Surface* minute3,SDL_Surface* minute4,SDL_Surface* minute5,SDL_Surface* minute6,SDL_Surface* minute7,SDL_Surface* minute8,SDL_Surface* minute9,Mix_Chunk* scratch_flash,Mix_Chunk* scratch_cristal,SDL_Surface* speed2,SDL_Surface* score_speed0,SDL_Surface* score_speed1,SDL_Surface* score_speed2,SDL_Surface* score_speed3,SDL_Surface* score_speed4,SDL_Surface* score_speed5,SDL_Surface* score_speed6,SDL_Surface* score_speed7,SDL_Surface* score_speed8,SDL_Surface* score_speed9,SDL_Surface* speed1,SDL_Surface* cristal1,SDL_Surface* cristal2,SDL_Surface* cristal3,SDL_Surface* cristal4,SDL_Surface* cristal5,int *et2,Mix_Music *musique,Mix_Music *ice,Mix_Chunk* scratch,Mix_Chunk* scratch_hit,Mix_Chunk* scratch_jump,Mix_Chunk* scratch_coin,Mix_Chunk* scratch_key,Mix_Chunk* scratch_etoile,Mix_Chunk* scratch_victory,Mix_Chunk* scratch_fail,int *coon,int *n2,SDL_Surface* win,SDL_Surface* etoile,SDL_Surface* etoile1,SDL_Surface* next_level,SDL_Surface* next_level1,SDL_Surface* home1,SDL_Surface* score_level,SDL_Surface* game_over,SDL_Surface* home,SDL_Surface* arr_plan,SDL_Surface* key1,SDL_Surface* key2,SDL_Surface* key3,SDL_Surface* key4,SDL_Surface* key5,SDL_Surface* key6,SDL_Surface* num0,SDL_Surface* num1,SDL_Surface* num2,SDL_Surface* num3,SDL_Surface* num4,SDL_Surface* num5,SDL_Surface* num6,SDL_Surface* num7,SDL_Surface* num8,SDL_Surface* num9,SDL_Surface* coin1,SDL_Surface* coin2,SDL_Surface* coin3,SDL_Surface* coin4,SDL_Surface* coin5,SDL_Surface* coin6,SDL_Surface* coin7,SDL_Surface* coin8,SDL_Surface* game_play,SDL_Surface* game_pause,SDL_Surface* heart,SDL_Surface* screen,SDL_Surface* background2,SDL_Surface* background22,SDL_Surface* perso,SDL_Surface* perso1,SDL_Surface* perso2,SDL_Surface* perso3,SDL_Surface* persop,SDL_Surface* perso1p,SDL_Surface* perso2p,SDL_Surface* perso3p,SDL_Surface* b2enemi11,SDL_Surface* b2enemi12,SDL_Surface* b2enemi13,SDL_Surface* b2enemi11p,SDL_Surface* b2enemi12p,SDL_Surface* b2enemi13p,SDL_Surface* b2enemi21,SDL_Surface* b2enemi22,SDL_Surface* b2enemi23,SDL_Surface* b2enemi21p,SDL_Surface* b2enemi22p,SDL_Surface* b2enemi23p,int *continuer);
/*---------------------------------*/
void level3(SDL_Surface* game_arr,SDL_Surface* game_home,Mix_Chunk* scratch_sword,SDL_Surface* sword,SDL_Surface* points,SDL_Surface* minute0,SDL_Surface* minute1,SDL_Surface* minute2,SDL_Surface* minute3,SDL_Surface* minute4,SDL_Surface* minute5,SDL_Surface* minute6,SDL_Surface* minute7,SDL_Surface* minute8,SDL_Surface* minute9,Mix_Chunk* scratch_flash,Mix_Chunk* scratch_cristal,SDL_Surface* speed2,SDL_Surface* score_speed0,SDL_Surface* score_speed1,SDL_Surface* score_speed2,SDL_Surface* score_speed3,SDL_Surface* score_speed4,SDL_Surface* score_speed5,SDL_Surface* score_speed6,SDL_Surface* score_speed7,SDL_Surface* score_speed8,SDL_Surface* score_speed9,SDL_Surface* speed1,SDL_Surface* cristal1,SDL_Surface* cristal2,SDL_Surface* cristal3,SDL_Surface* cristal4,SDL_Surface* cristal5,int *et3,Mix_Music *musique,Mix_Music *jungle,Mix_Chunk* scratch,Mix_Chunk* scratch_hit,Mix_Chunk* scratch_jump,Mix_Chunk* scratch_coin,Mix_Chunk* scratch_key,Mix_Chunk* scratch_etoile,Mix_Chunk* scratch_victory,Mix_Chunk* scratch_fail,int *coon,int *n3,SDL_Surface* win,SDL_Surface* etoile,SDL_Surface* etoile1,SDL_Surface* next_level,SDL_Surface* next_level1,SDL_Surface* home1,SDL_Surface* score_level,SDL_Surface* game_over,SDL_Surface* home,SDL_Surface* arr_plan,SDL_Surface* key1,SDL_Surface* key2,SDL_Surface* key3,SDL_Surface* key4,SDL_Surface* key5,SDL_Surface* key6,SDL_Surface* num0,SDL_Surface* num1,SDL_Surface* num2,SDL_Surface* num3,SDL_Surface* num4,SDL_Surface* num5,SDL_Surface* num6,SDL_Surface* num7,SDL_Surface* num8,SDL_Surface* num9,SDL_Surface* coin1,SDL_Surface* coin2,SDL_Surface* coin3,SDL_Surface* coin4,SDL_Surface* coin5,SDL_Surface* coin6,SDL_Surface* coin7,SDL_Surface* coin8,SDL_Surface* game_play,SDL_Surface* game_pause,SDL_Surface* heart,SDL_Surface* screen,SDL_Surface* background3,SDL_Surface* background33,SDL_Surface* perso,SDL_Surface* perso1,SDL_Surface* perso2,SDL_Surface* perso3,SDL_Surface* persop,SDL_Surface* perso1p,SDL_Surface* perso2p,SDL_Surface* perso3p,SDL_Surface* b3enemi11,SDL_Surface* b3enemi12,SDL_Surface* b3enemi13,SDL_Surface* b3enemi11p,SDL_Surface* b3enemi12p,SDL_Surface* b3enemi13p,SDL_Surface* b3enemi21,SDL_Surface* b3enemi22,SDL_Surface* b3enemi23,SDL_Surface* b3enemi21p,SDL_Surface* b3enemi22p,SDL_Surface* b3enemi23p,int *continuer);
/*---------------------------------*/
void level4(SDL_Surface* game_arr,SDL_Surface* game_home,Mix_Chunk* scratch_sword,SDL_Surface* sword,SDL_Surface* points,SDL_Surface* minute0,SDL_Surface* minute1,SDL_Surface* minute2,SDL_Surface* minute3,SDL_Surface* minute4,SDL_Surface* minute5,SDL_Surface* minute6,SDL_Surface* minute7,SDL_Surface* minute8,SDL_Surface* minute9,Mix_Chunk* scratch_flash,Mix_Chunk* scratch_cristal,SDL_Surface* speed2,SDL_Surface* score_speed0,SDL_Surface* score_speed1,SDL_Surface* score_speed2,SDL_Surface* score_speed3,SDL_Surface* score_speed4,SDL_Surface* score_speed5,SDL_Surface* score_speed6,SDL_Surface* score_speed7,SDL_Surface* score_speed8,SDL_Surface* score_speed9,SDL_Surface* speed1,SDL_Surface* cristal1,SDL_Surface* cristal2,SDL_Surface* cristal3,SDL_Surface* cristal4,SDL_Surface* cristal5,Mix_Chunk* scratch,Mix_Chunk* scratch_hit,Mix_Chunk* scratch_jump,Mix_Chunk* scratch_coin,Mix_Chunk* scratch_key,Mix_Chunk* scratch_etoile,Mix_Chunk* scratch_victory,Mix_Chunk* scratch_fail,int *coon,int *n4,SDL_Surface* win,SDL_Surface* etoile,SDL_Surface* etoile1,SDL_Surface* next_level,SDL_Surface* next_level1,SDL_Surface* home1,SDL_Surface* score_level,SDL_Surface* game_over,SDL_Surface* home,SDL_Surface* arr_plan,SDL_Surface* key1,SDL_Surface* key2,SDL_Surface* key3,SDL_Surface* key4,SDL_Surface* key5,SDL_Surface* key6,SDL_Surface* num0,SDL_Surface* num1,SDL_Surface* num2,SDL_Surface* num3,SDL_Surface* num4,SDL_Surface* num5,SDL_Surface* num6,SDL_Surface* num7,SDL_Surface* num8,SDL_Surface* num9,SDL_Surface* coin1,SDL_Surface* coin2,SDL_Surface* coin3,SDL_Surface* coin4,SDL_Surface* coin5,SDL_Surface* coin6,SDL_Surface* coin7,SDL_Surface* coin8,SDL_Surface* game_play,SDL_Surface* game_pause,SDL_Surface* heart,SDL_Surface* screen,SDL_Surface* background4,SDL_Surface* background44,SDL_Surface* perso,SDL_Surface* perso1,SDL_Surface* perso2,SDL_Surface* perso3,SDL_Surface* persop,SDL_Surface* perso1p,SDL_Surface* perso2p,SDL_Surface* perso3p,int *continuer);

#endif/*LEVEL_H_*/
